# i3status-rust config con colori da pywal
general = { interval = 5, output_format = "i3bar" }

# Lettura dei colori da wal
colors = { 
    background = "#$(jq -r .special.background ~/.cache/wal/colors.json)",
    foreground = "#$(jq -r .special.foreground ~/.cache/wal/colors.json)"
}

[[block]]
block = "time"
format = "{:%Y-%m-%d %H:%M:%S}"
full_text = "Clock"
foreground = "#$(jq -r .colors.color7 ~/.cache/wal/colors.json)"  # esempio: usa color7 per il testo

[[block]]
block = "cpu"
format = "CPU: {usage}%"
foreground = "#$(jq -r .colors.color1 ~/.cache/wal/colors.json)"

[[block]]
block = "memory"
format = "RAM: {used}/{total} MB"
foreground = "#$(jq -r .colors.color2 ~/.cache/wal/colors.json)"


[theme.overrides]
idle_bg = "#0A0D13"
idle_fg = "#d3d1d7"
info_bg = "#d3d1d7"
info_fg = "#A04959"
good_bg = "#4A738B"
good_fg = "#d3d1d7"
warning_bg = "#A04959"
warning_fg = "#0A0D13"
critical_bg = "#E49C6F"
critical_fg = "#d3d1d7"
alternating_tint_bg = "#0A0D13"
alternating_tint_fg = "#0A0D13"
